### PR TITLE
Adding the ability to use more than two profiles in koi and others see below 

### PR DESCRIPTION
**Pull request by Da-Viper**
i have been working on this for some time now  now although it is not yet completed , 
i want to know if i would be possible to merge this when it is done ? 

Current changes include: 
adding profiles
adding scripts 
switching widgets.
cursors.
window decorations 
moving to cmake.
code clean up 
ui change to make it simple 

Currently  it is almost done i am opening this merge request to keep track of the changes and  to know if it could be merged ?

### CODE REVIEW

**Comment by baduhai** [comment]
I think it could definitely be added to Koi. Do say when it's in a state where it could be merged, I'll review the changes and merge when ready, though it might be a lot to review. :sweat_smile:

**Comment by Da-Viper** [comment]
@baduhai , it would  probably be all done by next week, i want you to help me check if some things are missing that i missed out on 

**Currently missing** 
cancel dialog on changes made 
notifications 
don't enable wallpaper when not selected.

**Comment by Da-Viper** [comment]
Currently broken don't install

**Comment by Da-Viper** [comment]
Hello you can try it out now some things i have not implemented are 
konsole/ vs-code.( probably later ) can disable the gui before a release.

**Comment by Da-Viper** [comment]
@baduhai  can you check it out now

**Comment by baduhai** [comment]
So far everything I've seen in terms of code looks good, I'll continue with the testing and give you an answer soon.

**Comment by Da-Viper** [comment]
There may be some redundant methods I will remove that this weekend

**Comment by baduhai** [comment]
From my testing so far this seems ready to go, I see there are still commits coming from you, @Da-Viper. Is it in a state where you feel ready to merge?

**Comment by Da-Viper** [comment]
@baduhai  yeah it ready I just did some cleanup and checks

**Comment by baduhai** [comment]
@Da-Viper if you want to take the project on your own direction, go for it. I don't want to support it any more, I simply don't use Koi. If you do want to take your fork into your own direction, I can add a link on my readme to your repo, since mine will no longer be supported.

**Comment by baduhai** [comment]
@Da-Viper if you're still up for this, I'd be happy to merge this. With a rebase and proper changes of course, but I recently got some inspiration to work on Koi again.

**Pull request closed without merging**
