### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by toboil-features**
I added header to the autostart section and corrected instruction towards Plasma versions.

### CODE REVIEW

**Comment by MartinVonReichenberg** [comment]
Hello @toboil-features,

I will re-write the README and WIKI pages soon. 

Something of what you wrote I shall take into consideration.

Right now I am not currently in mood (having taste) for doing so, but in a week or two I should.

Cheers from Liberec

**Comment by toboil-features** [comment]
Hi, ok then. So I am closing this request?

**Comment by MartinVonReichenberg** [comment]
> Hi, ok then. So I am closing this request?

You can leave it open for now - as a reminder.

_You will notice . . ._

🙂

**Comment by toboil-features** [comment]
Haven't seen any change to README.md, any wish to merge?

**Comment by MartinVonReichenberg** [comment]
> Haven't seen any change to README.md, any wish to merge?

Hello, 

Everything will be done in about a week. 

I currently have more (distribution-wise) repositories to manage and maintain in their full potential.

**Comment by MartinVonReichenberg** [comment]
Done,
See [Releases](https://github.com/baduhai/Koi/releases/tag/0.3) for more information . . .

**Pull request closed without merging**
