### PR TITLE
Fix KDE/GTK missing themes

### PR DESCRIPTION
**Pull request by RodoMa92**
If the name of the themes precedes Breeze, it now doesen't cut out the first two entries. (maybe because it was originally skipping . and .. before calling the API with  QDir::NoDotAndDotDot?).

### CODE REVIEW

**Comment by baduhai** [comment]
Does the breeze plasma style still show up without the `plasmaStyles.append("breeze");` line?

**Comment by RodoMa92** [comment]
You are right, breeze has disappeared, whoops. Reverted that line.

**Comment by baduhai** [comment]
Thanks for the fix, I totally missed the bug.

**Comment by RodoMa92** [comment]
> Thanks for the fix, I totally missed the bug.

No problem, besides my confusion for why it wasn't working initially, the fix was quite easy. It has taken quite a bit of time to go read the source code, but whatever. It happens.

Thanks a lot for your software, by the way. I hope that Plasma will integrate this in their desktop sooner or later, but your software is working great in the meantime :P

Marco

**Comment by baduhai** [comment]
> Thanks a lot for your software, by the way. I hope that Plasma will integrate this in their desktop sooner or later, but your software is working great in the meantime :P

I'm actually trying to develop this functionality, but reading through and understanding all sections of the Plasma codebase is quite difficult...

**Comment by baduhai** [comment]
Just did some more testing, and it looks like you were accidentally correct. The `plasmaStyles.append("breeze");` line is no longer necessary. Breeze shows up under the name "default", but it shows up. I'll see if I replace the string for the name, or if I leave it as default, but the next release will no longer have the line you accidentally deleted :)

**Pull request merged**
