### PR TITLE
Allow tray icon customization

### PR DESCRIPTION
**Pull request by TaylanTatli**

### CODE REVIEW

**Comment by TaylanTatli** [comment]
> I don't understand... What exactly does this do?

If your system icon theme has an icon for `koi_tray` then app will use it, otherwise app will use default icon which is `/resources/icons/koi_tray.png`

**Comment by baduhai** [comment]
Why did you close it? Or maybe I closed it by accident and didn't notice?

I just didn't have time to review this, now that I had a new bout of inspiration for Koi I've been going through the code again, and reviewing merge requests, I'll get to yours eventually.

**Comment by TaylanTatli** [comment]
> Why did you close it? Or maybe I closed it by accident and didn't notice?
> 
> I just didn't have time to review this, now that I had a new bout of inspiration for Koi I've been going through the code again, and reviewing merge requests, I'll get to yours eventually.

I don't remember closing it, but I had deleted the repo.

**Comment by baduhai** [comment]
Maybe that closed it automatically. Regardless, thanks for supporting Koi in your icon pack! I think it's the first icon pack with support for koi.

**Comment by TaylanTatli** [comment]
I thank you for this app.

**Pull request merged**
