### PR TITLE
Fix issue #33.

### PR DESCRIPTION
**Pull request by vroger11**
Instead of using a fixed path to plasma-changeicons now Koi locate the program path.

### CODE REVIEW

**Comment by NicoVarg99** [comment]
`locate` is not suitable for this and some distros don't ship with it by default.
`whereis` is the right tool to do this job.

**Comment by baduhai** [comment]
Please fix as @NicoVarg99 says.

**Comment by vroger11** [comment]
Hello, I do not have much time currently to do it (I am finishing my PhD thesis). I will fix it in approximately 3 weeks if it is ok for you :)

**Comment by baduhai** [comment]
Good luck with your thesis.

**Comment by vroger11** [comment]
@baduhai, I managed to do it earlier than expected. Now, my fix uses `whereis` instead of `locate`.

**Comment by baduhai** [comment]
Perfect

**Pull request closed without merging**
